plugins {
    id 'com.android.application'
}

android {
    namespace 'com.umeed.peopleos'
    compileSdk 35

    defaultConfig {
        applicationId 'com.umeed.peopleos'
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName '5.9.2-R11'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
}
